### ISSUE TITLE
--wordpresspath missing on vhsetup.sh

### ISSUE THREAD

**Issue by peixotorms** [litespeedtech/ols1clk#56]
While it's possible to set a path for the wordpress install on the ols1clk, this is apparently not possible when we want to add a second site via the vhsetup.sh script. 

The vhsetup.sh script should support the same wordpress customizations as the the ols1clk script.

**Comment by Code-Egg** [comment]
Hi @peixotorms, 

Although the document path will be auto-generated by your specified domain name. It is possible to use vhsetup.sh script to set up a second virtual host. 
Since the vhsetup.sh script is designed for cloud image, maybe you can [try it next time](https://docs.litespeedtech.com/cloud/images/wordpress/#how-do-i-create-additional-virtual-hosts)

**Comment by peixotorms** [comment]
well, the issue exactly is that the path is auto-generated, while we should be able to customize it, similarly to the ols2clk script.

**Comment by Code-Egg** [comment]
Hi @peixotorms 
I just pushed a [commit](https://github.com/litespeedtech/ls-cloud-image/commit/382713bad75f2ff851c55ca1fd2dfb05b95fd8d7) . Feel free to give it a try and let me know if everything works, thanks. 
e.g. 
```
/bin/bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh ) -d www.example.com --path /var/www/html/abc
```
```
/bin/bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/vhsetup.sh ) -d www.example.com --path /var/www/html/abc -w
```
